from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox
import sys

from math import sqrt, factorial, log10


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setFixedSize(328, 398)  # resize если оконо изменяемое
        MainWindow.setStyleSheet("\n"
                                 "background-color: rgb(180, 128, 254);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.input = QtWidgets.QLabel(self.centralwidget)
        self.input.setGeometry(QtCore.QRect(0, 0, 331, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.input.setFont(font)
        self.input.setStyleSheet("background-color: rgb(79, 199, 135);")
        self.input.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.input.setObjectName("input")
        self.btn_1 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_1.setGeometry(QtCore.QRect(10, 100, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.btn_1.setFont(font)
        self.btn_1.setStyleSheet("background-color: rgb(205, 78, 85);")
        self.btn_1.setObjectName("btn_1")
        self.btn_2 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_2.setGeometry(QtCore.QRect(60, 100, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.btn_2.setFont(font)
        self.btn_2.setStyleSheet("background-color: rgb(205, 78, 85);")
        self.btn_2.setObjectName("btn_2")
        self.btn_3 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_3.setGeometry(QtCore.QRect(10, 150, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.btn_3.setFont(font)
        self.btn_3.setStyleSheet("background-color: rgb(205, 78, 85);")
        self.btn_3.setObjectName("btn_3")
        self.btn_4 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_4.setGeometry(QtCore.QRect(60, 150, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.btn_4.setFont(font)
        self.btn_4.setStyleSheet("background-color: rgb(205, 78, 85);")
        self.btn_4.setObjectName("btn_4")
        self.btn_8 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_8.setGeometry(QtCore.QRect(60, 250, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.btn_8.setFont(font)
        self.btn_8.setStyleSheet("background-color: rgb(205, 78, 85);")
        self.btn_8.setObjectName("btn_8")
        self.btn_6 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_6.setGeometry(QtCore.QRect(60, 200, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.btn_6.setFont(font)
        self.btn_6.setStyleSheet("background-color: rgb(205, 78, 85);")
        self.btn_6.setObjectName("btn_6")
        self.btn_5 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_5.setGeometry(QtCore.QRect(10, 200, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.btn_5.setFont(font)
        self.btn_5.setStyleSheet("background-color: rgb(205, 78, 85);")
        self.btn_5.setObjectName("btn_5")
        self.btn_7 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_7.setGeometry(QtCore.QRect(10, 250, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.btn_7.setFont(font)
        self.btn_7.setStyleSheet("background-color: rgb(205, 78, 85);")
        self.btn_7.setObjectName("btn_7")
        self.btn_9 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_9.setGeometry(QtCore.QRect(10, 300, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.btn_9.setFont(font)
        self.btn_9.setStyleSheet("background-color: rgb(205, 78, 85);")
        self.btn_9.setObjectName("btn_9")
        self.btn_0 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_0.setGeometry(QtCore.QRect(60, 300, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.btn_0.setFont(font)
        self.btn_0.setStyleSheet("background-color: rgb(205, 78, 85);")
        self.btn_0.setObjectName("btn_0")
        self.label_d = QtWidgets.QPushButton(self.centralwidget)
        self.label_d.setGeometry(QtCore.QRect(220, 200, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_d.setFont(font)
        self.label_d.setStyleSheet("background-color: rgb(205, 78, 85);")
        self.label_d.setObjectName("label_d")
        self.label_v = QtWidgets.QPushButton(self.centralwidget)
        self.label_v.setGeometry(QtCore.QRect(220, 150, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_v.setFont(font)
        self.label_v.setStyleSheet("background-color: rgb(205, 78, 85);")
        self.label_v.setObjectName("label_v")
        self.label_m = QtWidgets.QPushButton(self.centralwidget)
        self.label_m.setGeometry(QtCore.QRect(120, 200, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_m.setFont(font)
        self.label_m.setStyleSheet("background-color: rgb(205, 78, 85);")
        self.label_m.setObjectName("label_m")
        self.label_d_2 = QtWidgets.QPushButton(self.centralwidget)
        self.label_d_2.setGeometry(QtCore.QRect(120, 150, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_d_2.setFont(font)
        self.label_d_2.setStyleSheet("background-color: rgb(205, 78, 85);")
        self.label_d_2.setObjectName("label_d_2")
        self.btn_sqr = QtWidgets.QPushButton(self.centralwidget)
        self.btn_sqr.setGeometry(QtCore.QRect(170, 250, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.btn_sqr.setFont(font)
        self.btn_sqr.setStyleSheet("background-color: rgb(205, 78, 85);")
        self.btn_sqr.setObjectName("btn_sqr")
        self.btn_c = QtWidgets.QPushButton(self.centralwidget)
        self.btn_c.setGeometry(QtCore.QRect(120, 100, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.btn_c.setFont(font)
        self.btn_c.setStyleSheet("background-color: rgb(205, 78, 85);")
        self.btn_c.setObjectName("btn_c")
        self.btn_e = QtWidgets.QPushButton(self.centralwidget)
        self.btn_e.setGeometry(QtCore.QRect(170, 300, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.btn_e.setFont(font)
        self.btn_e.setStyleSheet("background-color: rgb(205, 78, 85);")
        self.btn_e.setObjectName("btn_e")
        self.btn_pi = QtWidgets.QPushButton(self.centralwidget)
        self.btn_pi.setGeometry(QtCore.QRect(120, 300, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.btn_pi.setFont(font)
        self.btn_pi.setStyleSheet("background-color: rgb(205, 78, 85);")
        self.btn_pi.setObjectName("btn_pi")
        self.btn_abs = QtWidgets.QPushButton(self.centralwidget)
        self.btn_abs.setGeometry(QtCore.QRect(270, 300, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.btn_abs.setFont(font)
        self.btn_abs.setStyleSheet("background-color: rgb(205, 78, 85);")
        self.btn_abs.setObjectName("btn_abs")
        self.btn_lg = QtWidgets.QPushButton(self.centralwidget)
        self.btn_lg.setGeometry(QtCore.QRect(220, 250, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.btn_lg.setFont(font)
        self.btn_lg.setStyleSheet("background-color: rgb(205, 78, 85);")
        self.btn_lg.setObjectName("btn_lg")
        self.btn_sqrt = QtWidgets.QPushButton(self.centralwidget)
        self.btn_sqrt.setGeometry(QtCore.QRect(220, 300, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.btn_sqrt.setFont(font)
        self.btn_sqrt.setStyleSheet("background-color: rgb(205, 78, 85);")
        self.btn_sqrt.setObjectName("btn_sqrt")
        self.btn_f = QtWidgets.QPushButton(self.centralwidget)
        self.btn_f.setGeometry(QtCore.QRect(120, 250, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.btn_f.setFont(font)
        self.btn_f.setStyleSheet("background-color: rgb(205, 78, 85);")
        self.btn_f.setObjectName("btn_f")
        self.btn_r = QtWidgets.QPushButton(self.centralwidget)
        self.btn_r.setGeometry(QtCore.QRect(220, 100, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.btn_r.setFont(font)
        self.btn_r.setStyleSheet("background-color: rgb(205, 78, 85);")
        self.btn_r.setObjectName("btn_r")
        self.btn_ce = QtWidgets.QPushButton(self.centralwidget)
        self.btn_ce.setGeometry(QtCore.QRect(170, 100, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.btn_ce.setFont(font)
        self.btn_ce.setStyleSheet("background-color: rgb(205, 78, 85);")
        self.btn_ce.setObjectName("btn_ce")
        self.output = QtWidgets.QLabel(self.centralwidget)
        self.output.setGeometry(QtCore.QRect(0, 50, 331, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.output.setFont(font)
        self.output.setStyleSheet("background-color: rgb(79, 199, 135);")
        self.output.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.output.setObjectName("output")
        self.btn_brl = QtWidgets.QPushButton(self.centralwidget)
        self.btn_brl.setGeometry(QtCore.QRect(270, 250, 21, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.btn_brl.setFont(font)
        self.btn_brl.setStyleSheet("background-color: rgb(205, 78, 85);")
        self.btn_brl.setObjectName("btn_brl")
        self.btn_brr = QtWidgets.QPushButton(self.centralwidget)
        self.btn_brr.setGeometry(QtCore.QRect(290, 250, 21, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.btn_brr.setFont(font)
        self.btn_brr.setStyleSheet("background-color: rgb(205, 78, 85);")
        self.btn_brr.setObjectName("btn_brr")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 328, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Калькулятор"))
        self.input.setText(_translate("MainWindow", ""))
        self.btn_1.setText(_translate("MainWindow", "1"))
        self.btn_2.setText(_translate("MainWindow", "2"))
        self.btn_3.setText(_translate("MainWindow", "3"))
        self.btn_4.setText(_translate("MainWindow", "4"))
        self.btn_8.setText(_translate("MainWindow", "8"))
        self.btn_6.setText(_translate("MainWindow", "6"))
        self.btn_5.setText(_translate("MainWindow", "5"))
        self.btn_7.setText(_translate("MainWindow", "7"))
        self.btn_9.setText(_translate("MainWindow", "9"))
        self.btn_0.setText(_translate("MainWindow", "0"))
        self.label_d.setText(_translate("MainWindow", "\\"))
        self.label_v.setText(_translate("MainWindow", "-"))
        self.label_m.setText(_translate("MainWindow", "*"))
        self.label_d_2.setText(_translate("MainWindow", "+"))
        self.btn_sqr.setText(_translate("MainWindow", "^"))
        self.btn_c.setText(_translate("MainWindow", "C"))
        self.btn_e.setText(_translate("MainWindow", "е"))
        self.btn_pi.setText(_translate("MainWindow", "Пі"))
        self.btn_abs.setText(_translate("MainWindow", "|x|"))
        self.btn_lg.setText(_translate("MainWindow", "lg"))
        self.btn_sqrt.setText(_translate("MainWindow", "√"))
        self.btn_f.setText(_translate("MainWindow", "n!"))
        self.btn_r.setText(_translate("MainWindow", "="))
        self.btn_ce.setText(_translate("MainWindow", "CE"))
        self.output.setText(_translate("MainWindow", "="))
        self.btn_brl.setText(_translate("MainWindow", "("))
        self.btn_brr.setText(_translate("MainWindow", ")"))


class Window(QtWidgets.QMainWindow):
    def __init__(self):
        super(Window, self).__init__()
        self.ui = Ui_MainWindow()
        self.ui.setupUi(self)
        self.ui.btn_1.clicked.connect(lambda: self.num_but(1))
        self.ui.btn_2.clicked.connect(lambda: self.num_but(2))
        self.ui.btn_3.clicked.connect(lambda: self.num_but(3))
        self.ui.btn_4.clicked.connect(lambda: self.num_but(4))
        self.ui.btn_5.clicked.connect(lambda: self.num_but(5))
        self.ui.btn_6.clicked.connect(lambda: self.num_but(6))
        self.ui.btn_7.clicked.connect(lambda: self.num_but(7))
        self.ui.btn_8.clicked.connect(lambda: self.num_but(8))
        self.ui.btn_9.clicked.connect(lambda: self.num_but(9))
        self.ui.btn_0.clicked.connect(lambda: self.num_but(0))
        self.ui.label_d.clicked.connect(lambda: self.num_but("/"))
        self.ui.label_v.clicked.connect(lambda: self.num_but("-"))
        self.ui.label_m.clicked.connect(lambda: self.num_but("*"))
        self.ui.label_d_2.clicked.connect(lambda: self.num_but("+"))
        self.ui.btn_pi.clicked.connect(lambda: self.num_but("3.14"))
        self.ui.btn_sqr.clicked.connect(lambda: self.num_but("**"))
        self.ui.btn_c.clicked.connect(lambda: self.clear_all())
        self.ui.btn_e.clicked.connect(lambda: self.num_but("2.76"))
        self.ui.btn_abs.clicked.connect(self.absolute_value)
        self.ui.btn_lg.clicked.connect(self.lg)
        self.ui.btn_sqrt.clicked.connect(self.square_root)
        self.ui.btn_f.clicked.connect(self.factor)
        self.ui.btn_r.clicked.connect(self.equare)
        self.ui.btn_ce.clicked.connect(self.clear_e)
        self.ui.btn_brr.clicked.connect(lambda: self.num_but(")"))
        self.ui.btn_brl.clicked.connect(lambda: self.num_but("("))

    def equare(self):
        self.ui.output.clear()
        try:
            a = eval(self.ui.input.text())
        except ZeroDivisionError:
            self.zero_divivsion()
        except ValueError:
            self.nothing()
        self.ui.output.setText(self.ui.output.text() + str(a))
        self.ui.input.clear()

    def clear_all(self):
        a = str(self.ui.input.text())
        if len(a) > 0:
            self.ui.input.clear()
        else:
            self.zero_divivsion()
    def clear_e(self):
        a = str(self.ui.input.text())
        if len(a) > 0:
            self.ui.input.setText(a[:-1])
        else:
            self.nothing()


    def factor(self):
        n = factorial(int(self.ui.input.text()))
        print(n)
        self.ui.input.setText(str(n))
        self.message("Factorial",
                     "Example:\n!5=1*2*3*4*5")

    def lg(self):
        if int(self.ui.input.text()) == 0:
            self.ZeroDivivsion()
        n = log10(int(self.ui.input.text()))
        self.ui.input.setText(str(n))
        self.ui.input.setText(str(n))
        self.message("Logarithm",
                     "In mathematics, the logarithm is "
                     "the inverse function to exponentiation")

    def square_root(self):
        n = sqrt(int(self.ui.input.text()))
        self.ui.input.setText(str(n))
        self.message("Square root",
                     "In mathematics, a square root of a number "
                     "x is a number y such that y^2 = x")

    def absolute_value(self):
        n = abs(int(self.ui.input.text()))
        self.ui.input.setText(str(n))
        self.ui.input.setText(str(n))
        self.message("Absolute value",
                     "Absolute value describes the distance from zero that a "
                     "number is on the number line, without considering direction")

    def num_but(self, num):
        v = str(num)
        self.ui.input.setText(self.ui.input.text() + v)

    def zero_divivsion(self):
        error = QMessageBox()
        error.setWindowTitle("Division by zero")
        error.setText("Can't divide by zero")
        error.exec()
    def nothing(self):
        error = QMessageBox()
        error.setWindowTitle("Error")
        error.setText("You have already erased everything")
        error.setIcon(QMessageBox.Warning)

        error.setInformativeText(
            'If you have erased the last digit, you should STOP ')
        error.exec()

    def message(self, title, text):
        info = QMessageBox()
        info.setWindowTitle(title)
        info.setText(text)
        info.setIcon(QMessageBox.Information)
        info.exec()




app = QtWidgets.QApplication(sys.argv)
application = Window()
application.show()
sys.exit(app.exec())
