# Generated by Django 4.1.1 on 2022-10-22 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FSM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fsm_flag', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'FSM_readonly',
                'verbose_name_plural': 'FSM_readonly',
            },
        ),
        migrations.CreateModel(
            name='RecipeBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name="Ім'я")),
                ('last_name', models.CharField(max_length=255, verbose_name='Прізвище')),
                ('user_name', models.CharField(max_length=255, verbose_name='username')),
                ('user_id', models.IntegerField(verbose_name='User Id')),
                ('profile_name', models.CharField(max_length=255, verbose_name="Ім'я з анкети")),
                ('gender', models.CharField(max_length=255, verbose_name='Стать')),
            ],
            options={
                'verbose_name': 'Список користувачів',
                'verbose_name_plural': 'Список користувачів',
                'ordering': ['name', 'last_name', 'user_name', 'user_id', 'profile_name', 'gender'],
            },
        ),
        migrations.CreateModel(
            name='RecipeBook_recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Назва')),
                ('photo', models.ImageField(upload_to='photo', verbose_name='Фото')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
            ],
            options={
                'verbose_name': 'Список страв',
                'verbose_name_plural': 'Список страв',
                'ordering': ['id', 'title', 'description'],
            },
        ),
    ]
